services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    
  auction-svc:
    image: auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    ports:
      - "7001:80"
      - "7777:7777"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=server=postgres;port=5432;database=Auctions;user id=postgres;password=postgres;
      - RabbitMq__Host=rabbitmq
      - IdentityServiceUrl=http://identiy-svc
      - Kestrel_Endpoints_Grpc_Protocols=Http2
      - Kestrel_Endpoints_Grpc_Url=http://+7777
      - Kestrel_Endpoints_WebApi_Protocols=Http1
      - Kestrel_Endpoints_WebApi_Url=http://+80
    depends_on:
      - postgres
      - rabbitmq

  search-svc:
    image: search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    ports:
      - "7002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb:27017
      - RabbitMq__Host=rabbitmq
      - IdentityServiceUrl=http://identiy-svc
      - AuctionServiceUrl=http://auction-svc
    depends_on:
      - postgres
      - rabbitmq
  identiy-svc:
    image: identity-svc:latest
    build:
      context: . 
      dockerfile: src/IdentityService/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=server=postgres;port=5432;database=IdentityDb;user id=postgres;password=postgres;
    depends_on:
      - postgres

  gateway-svc:
    image: gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    ports:
      - "6001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - IdentityServiceUrl=http://identiy-svc
    depends_on:
      - identiy-svc
      - auction-svc
      - search-svc  

  bid-svc:
    image: bid-svc:latest
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
    ports:
      - "7003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__BidDbConnection=mongodb://root:mongopw@mongodb:27017
      - RabbitMq__Host=rabbitmq
      - IdentityServiceUrl=http://identiy-svc
      - AuctionServiceUrl=http://auction-svc
      - GrpcAuction=http://auction-svc:7777
    depends_on:
      - postgres
      - rabbitmq

volumes:
  pgdata:
  mongodata: