version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  auction-svc:
    image: keorapetse159/auction-svc:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres;User Id=postgres;Password=postgres;Database=auctions
      - IdentityServiceUrl=http://identity-svc
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=http://+:80
    ports:
      - "7001:80"
      - "7777:7777"
    depends_on:
      - postgres
      - rabbitmq

  search-svc:
    image: keorapetse159/search-svc:latest
    ports:
      - "7002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb:27017
      - RabbitMq__Host=rabbitmq
      - IdentityServiceUrl=http://identity-svc
      - AuctionServiceUrl=http://auction-svc
    depends_on:
      - mongodb
      - rabbitmq

  identity-svc:
    image: keorapetse159/identity-svc:latest
    ports: 
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - IssuerUri=http://localhost:5001
      - ClientApp=http://localhost:3000
      # - VIRTUAL_HOST=localhost:
      - ConnectionStrings__DefaultConnection=server=postgres;port=5432;database=IdentityDb;user id=postgres;password=postgres;
    depends_on:
      - postgres

  gateway-svc:
    image: keorapetse159/gateway-svc:latest
    ports:
      - "6001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=http://localhost
      - VIRTUAL_HOST=localhost
    depends_on:
      - identity-svc
      - auction-svc
      - search-svc

  bid-svc:
    image: keorapetse159/bid-svc:latest
    ports:
      - "7003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__BidDbConnection=mongodb://root:mongopw@mongodb:27017
      - RabbitMq__Host=rabbitmq
      - IdentityServiceUrl=http://identity-svc
      - AuctionServiceUrl=http://auction-svc
      - GrpcAuction=http://auction-svc:7777
    depends_on:
      - mongodb
      - rabbitmq

  notify-svc:
    image: keorapetse159/notify-svc:latest
    ports:
      - "7004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - rabbitmq

  web-app:
    image: keorapetse159/web-app:latest
    volumes:
      - /var/lib/web/data
    ports:
      - "3000:3000"
    environment:
      - AUTH_SECRET="4lj/CDAoZoHwXgsr3CjBbc1Je/ggJgWG1t12Viv1smc="
      - AUTH_URL=http://localhost:3000
      - AUTH_URL_INTERNAL=http://web-app:3000
      - API_URL=http://gateway-svc/
      - ID_URL=http://localhost:5001
      - ID_URL_INTERNAL=http://identity-svc
      - NEXT_PUBLIC_NOTIFY_URL=http://gateway-svc/notifications
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=3000

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  pgdata:
  mongodata:
